export default [{
  "id": 100,
  "title": "首页",
  "iconType": "sketch",
  "name": "home",
  "path": "/",
  "component": "home",
  "children": []
}, {
  "id": 200,
  "title": "分组一",
  "iconType": "area-chart",
  "component": "",
  "children": [{
    "id": 210,
    "title": "页面-1",
    "iconType": "pie-chart",
    "name": "example1",
    "path": "/example1",
    "component": "exampleView",
    "children": []
  }]
}, {
  "id": 300,
  "title": "分组二",
  "iconType": "sliders",
  "component": "",
  "children": [{
    "id": 310,
    "title": "页面-2",
    "iconType": "sliders",
    "name": "example2",
    "path": "/example2",
    "component": "exampleView",
    "children": []
  }, {
    "id": 320,
    "title": "子分组",
    "iconType": "fund",
    "component": "home",
    "children": [{
      "id": 321,
      "title": "页面-3",
      "iconType": "",
      "name": "example3",
      "path": "/example3",
      "component": "exampleView",
      "children": []
    }, {
      "id": 322,
      "title": "页面-4",
      "iconType": "",
      "name": "example4",
      "path": "/example4",
      "component": "exampleView",
      "children": []
    }, {
      "id": 323,
      "title": "页面-5",
      "iconType": "",
      "name": "example5",
      "path": "/example5",
      "component": "exampleView",
      "children": []
    }]
  }]
}, {
  "id": 400,
  "title": "分组三",
  "iconType": "github",
  "component": "account-book",
  "children": [{
    "id": 410,
    "title": "页面-6",
    "iconType": "alert",
    "name": "example6",
    "path": "/example6",
    "component": "exampleView",
    "children": []
  }, {
    "id": 420,
    "title": "页面-7",
    "iconType": "api",
    "name": "example7",
    "path": "/example7",
    "component": "exampleView",
    "children": []
  }, {
    "id": 430,
    "title": "页面-8",
    "iconType": "appstore",
    "name": "example8",
    "path": "/example8",
    "component": "exampleView",
    "children": []
  }, {
    "id": 440,
    "title": "页面-9",
    "iconType": "audio",
    "name": "example9",
    "path": "/example9",
    "component": "exampleView",
    "children": []
  }, {
    "id": 450,
    "title": "页面-10",
    "iconType": "bank",
    "name": "example10",
    "path": "/example10",
    "component": "exampleView",
    "children": []
  }, {
    "id": 460,
    "title": "页面-11",
    "iconType": "bell",
    "name": "example11",
    "path": "/example11",
    "component": "exampleView",
    "children": []
  }, {
    "id": 470,
    "title": "页面-12",
    "iconType": "book",
    "name": "example12",
    "path": "/example12",
    "component": "exampleView",
    "children": []
  }, {
    "id": 480,
    "title": "页面-13",
    "iconType": "bug",
    "name": "example13",
    "path": "/example13",
    "component": "exampleView",
    "children": []
  }, {
    "id": 490,
    "title": "页面-14",
    "iconType": "bulb",
    "name": "example14",
    "path": "/example14",
    "component": "exampleView",
    "children": []
  }]
}]